### ISSUE TITLE
Salesforce integration dead after update to v4

### ISSUE THREAD

**Issue by benbehringer** [mautic/mautic#10730]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

After upgrading to v4 the Salesforce integration stopped working.
The frontend just shows an empty popup when opening the Salesforce plugin.

Here's what I receive using the console:
```
php /var/www/html/bin/console mautic:integration:fetchleads -i Salesforce
Command to fetch contacts from integration
Fetch contacts command is starting

In AbstractIntegration.php line 2007:
                                                                                                                              
  Typed property Mautic\PluginBundle\Integration\AbstractIntegration::$adminUsers must not be accessed before initialization  
                                                                                                                              

mautic:integration:fetchleads [-i|--integration INTEGRATION] [-d|--start-date START-DATE] [-t|--end-date END-DATE] [--fetch-all] [-a|--time-interval [TIME-INTERVAL]] [-l|--limit [LIMIT]] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### How can we reproduce this issue?

Step 1: run Mautic v4 docker image
Step 2: try using the Salesforce integration

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by benbehringer** [comment]
Fixed it by resetting the plugin (using the mysql monitor):
```
update plugin_integration_settings set is_published=0 where name='salesforce';
update plugin_integration_settings set api_keys="a:0:{}" where name='salesforce';
```
The plugin showed up again and I had to recreate credentials in Salesforce.

**Comment by alfredoct96** [comment]
Hi, recreate Salesforce credentials is just a temporary solution, next day that i did it the problem came back @benbehringer
