### ISSUE TITLE
API call does not handle fields correctly

### ISSUE THREAD

**Issue by gerard-kanters** [mautic/mautic#1243]
When using the tracking pixel and construct the API call like this

/mtracking.gif?page_url=http://www.test.elgg.org/admin/plugins&page_title=Plugin-instellinge:Test&email=gkanters%40netcare.nl&firstname=Administrator&lastname=%20&location=Amsterdam

As you can see lastname is a space (which I did not include nut anyhow appears). 

When checking the lead in leads it adds the location to lastname. See below

![image](https://cloud.githubusercontent.com/assets/4699801/11788489/98f73f56-a291-11e5-8e55-5ce3f6a57488.png)

This happens both on the master repo as the staging repo.

**Comment by escopecz** [comment]
This was fixed in 1.2.0: https://github.com/mautic/mautic/pull/802. What version do you use?

**Comment by gerard-kanters** [comment]
This is tested on the staging repo. I also have a 1.2.2 version running. 

As you can see, in the current staging repo  the bug is back 

https://github.com/escopecz/mautic/blob/master/app/bundles/FormBundle/Views/SubscribedEvents/Timeline/index.html.php#L54

**Comment by escopecz** [comment]
Master seems to be still in version 1.0.0. Staging has the new code:

https://github.com/escopecz/mautic/blob/staging/app/bundles/FormBundle/Views/SubscribedEvents/Timeline/index.html.php

**Comment by escopecz** [comment]
I just realized you are using my personal Mautic repo where the master branch hasn't been updated for a while. Please, use the official https://github.com/mautic/mautic repo

**Comment by gerard-kanters** [comment]
I am using the official repo. My mistake to copy the wrong url (because I was folling issue 802). The official repo seems to have the non fixed code (check on empty is lacking)

https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Views/SubscribedEvents/Timeline/index.html.php#L56

Please take another look, or test it. The official master and staging still have the issue.

**Comment by escopecz** [comment]
No, they don't. You are looking at a wrong line. It's here:

https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Views/SubscribedEvents/Timeline/index.html.php#L54

and it is the same as the fix from the PR I posted above:

https://github.com/mautic/mautic/pull/802/files#diff-f4d8701cb43f4306273ce36001724d01R54

**Comment by gerard-kanters** [comment]
Yes, code seems ok. I am not familiar yet with Mautic, but isn't this code related to input from forms ?
 
I am having the problem with the tracking pixel. Maybe a similar solution can apply.

**Comment by escopecz** [comment]
Yes, you are right, a similar fix has to be made to the page timeline template:

https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/index.html.php#L113-L122

I'll mark this issue as reported bug.
