### ISSUE TITLE
Clone Trigger + Report - Error

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12809]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

(Reported similar problem: #12770 )
Mautic 5 Beta 1

When attempting to clone point triggers or reports, an issue arises during the cloning process. Although no error is displayed to the user, the cloning process does not complete successfully.

![image](https://github.com/mautic/mautic/assets/131262825/7b48452d-8f5f-4889-a845-d419874aaccc)

### How can we reproduce this issue?

Step 1: Create a new point trigger / report.
Step 2: Configurate it.
Step 3: Save and Close
Step 4: Clone your point trigger / report. Nothing happens at first glance, however, it displays an error occurs during the clone process on the Error Log and on the browser console.

### Relevant log output

```shell
[2023-10-18T15:48:31.011249+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\PointBundle\Controller\TriggerController::newAction(): Argument #1 ($request) must be of type Symfony\Component\HttpFoundation\Request, Mautic\PointBundle\Entity\Trigger given, called in /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php on line 466" at /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php line 167 {"exception":"[object] (TypeError(code: 0): Mautic\\PointBundle\\Controller\\TriggerController::newAction(): Argument #1 ($request) must be of type Symfony\\Component\\HttpFoundation\\Request, Mautic\\PointBundle\\Entity\\Trigger given, called in /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php on line 466 at /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php:167)"} {"hostname":"1a439a5962a4","pid":2481}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug, hopefully we can get this sorted before the release candidate!

**Comment by mollux** [comment]
@code5rick this looks like the issue addressed in https://github.com/mautic/mautic/pull/12772

could you recheck with Mautic 5.0.0-beta2?

**Comment by code5rick** [comment]
Hi @mollux 

On M5b2 the issue with cloning point triggers and reports still persists.

**Points manage triggers:**
![image](https://github.com/mautic/mautic/assets/131262825/4f3a1900-9c50-453e-a07d-3717c3d4efd4)
```php
[2023-10-19T09:35:22.654786+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\PointBundle\Controller\TriggerController::newAction(): Argument #1 ($request) must be of type Symfony\Component\HttpFoundation\Request, Mautic\PointBundle\Entity\Trigger given, called in /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php on line 466" at /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php line 167 {"exception":"[object] (TypeError(code: 0): Mautic\\PointBundle\\Controller\\TriggerController::newAction(): Argument #1 ($request) must be of type Symfony\\Component\\HttpFoundation\\Request, Mautic\\PointBundle\\Entity\\Trigger given, called in /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php on line 466 at /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php:167)"} {"hostname":"8d0f74ea457d","pid":66}
``` 

**Report:**
![image](https://github.com/mautic/mautic/assets/131262825/86fe1937-db02-415c-ae89-9d531fac6df6)
```php
[2023-10-19T09:40:18.886025+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\ReportBundle\Controller\ReportController::newAction(): Argument #1 ($request) must be of type Symfony\Component\HttpFoundation\Request, Mautic\ReportBundle\Entity\Report given, called in /var/www/html/app/bundles/ReportBundle/Controller/ReportController.php on line 152" at /var/www/html/app/bundles/ReportBundle/Controller/ReportController.php line 441 {"exception":"[object] (TypeError(code: 0): Mautic\\ReportBundle\\Controller\\ReportController::newAction(): Argument #1 ($request) must be of type Symfony\\Component\\HttpFoundation\\Request, Mautic\\ReportBundle\\Entity\\Report given, called in /var/www/html/app/bundles/ReportBundle/Controller/ReportController.php on line 152 at /var/www/html/app/bundles/ReportBundle/Controller/ReportController.php:441)"} {"hostname":"8d0f74ea457d","pid":57}
```

**Comment by mollux** [comment]
@code5rick aha indeed.

I addressed the issue in #12811
