### ISSUE TITLE
Apply button in GrapesJS builder causes an error and doesn't save

### ISSUE THREAD

**Issue by csgerg** [mautic/mautic#13271]
### Mautic Version

5.0.x series

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Firefox

### What happened?

I got Javascript error after editing with the GrapesJS editor the default Blank template. The error code appears in the browser's console, after I press the Apply button in the right-upper corner. The check icon turns to never ending spinner.

### How can we reproduce this issue?

Step 1:  Open the Blank email template.
Step 2:  Press the "Apply changes" button in the right-upper corner.

### Relevant log output

```shell
Uncaught TypeError: History.pushState is not a function
    postFormResponse buttonApply.command.js:68
    success app.js:288
    success libraries.js:1626
    fire libraries.js:271
    fireWith libraries.js:276
    done libraries.js:667
    callback libraries.js:680
    send libraries.js:680
    ajax libraries.js:658
    ajaxSubmit libraries.js:1628
    postForm app.js:284
    postForm buttonApply.command.js:47
    applyForm buttonApply.command.js:32
    callRun CommandAbstract.js:90
    runCommand index.js:388
    updateActive ButtonView.js:120
    Backbone 5
    toggleActive ButtonView.js:168
    clicked ButtonView.js:159
    Underscore 3
    t cash-dom.js:794
buttonApply.command.js:68:16
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by arius28** [comment]
I also experienced this issue. It seems to be that History.pushState should be history.pushstate since I don't see anything similar somewhere else. Replacing History with history seems to make it work.

The line shows up in plugins\GrapesJsBuilderBundle\Assets\library\js\dist\builder.js in my installation and in the mautic repository. 

If I 'm not mistaken (and I could be) I see that it is correct in https://github.com/mautic/grapesjs-preset-mautic/blob/b1ee6781eb4539586073b36302fdbba566901e6a/src/buttons/buttonApply.command.js#L75 from where it presumably originates.

Perhaps the dist\builder.js should be regenerated?

**Comment by DaianaVanoniPuggioni** [comment]
I made the same change that user arius28 mentioned but it's still failing.

**Comment by arius28** [comment]
@DaianaVanoniPuggioni I am trying to remember if I did some other change as well but nothing else comes to mind. I definitely cleared the browser cache and probably also cleaned the mautic cache as well using the command line (mautic:cache:clear). If you cannot try the command line you can also try to delete everything inside the folder /var/cache/.

I hope this helps until the Mautic team can check this out.

**Comment by annamunk** [comment]
@mollux it looks like this issue and https://github.com/mautic/mautic/issues/12928 have already been resolved by https://github.com/mautic/grapesjs-preset-mautic/pull/45, but changes are missing from [the build.js](https://github.com/mautic/mautic/blob/5.x/plugins/GrapesJsBuilderBundle/Assets/library/js/dist/builder.js) file in the Mautic repository. Will this update be included in the 5.x branch?

**Comment by lordimac** [comment]
Hope so, this bug is annoying!

**Comment by andrepedrofeza** [comment]
Hello! 

I installed Mautic from the 5.0.3 branch and had the same problem with the save button loading forever. So I installed it again from the 5.x branch, but the problem persists.
Can anyone help me how to adjust this? Because the correction was made in the repository https://github.com/mautic/grapesjs-preset-mautic, but not in the Mautic repository (https://github.com/mautic/mautic), and I have no idea how to adjust this on my Mautic.

If anyone can help me I would appreciate it, thanks.
