### ISSUE TITLE
Error 500 when creating a new email with some templates

### ISSUE THREAD

**Issue by GhaziTriki** [mautic/mautic#14444]
### Mautic Series

5.2.x series

### Mautic installed version

5.2.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.3.0

### What browsers are you seeing the problem on?

Firefox

### What happened?

Server returns Error 500 when creating a new mail with some templates.

### How can we reproduce this issue?

I proceed to creating " New Email " however I get an error "Your request could not be processed, please try again" when selecting template "1:2", "1:3" and few others. It works well with "1:2:1" as example.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by Jaishree2310** [comment]
@GhaziTriki Please assign this issue to me, I would like to work.

**Comment by RCheesley** [comment]
This is probably due to a missing defaults folder on Composer installs, related also to https://github.com/mautic/mautic/issues/14419, and fixed by #14425 - could you test and see if this fixes it? Testing instructions at https://mau.tc/tester. Thanks!

**Comment by RCheesley** [comment]
> @GhaziTriki Please assign this issue to me, I would like to work.

I think this is already fixed @Jaishree2310 but there's plenty more open todos :)

**Comment by GhaziTriki** [comment]
Hello, updated to Mautic 5.2.2 but the issue is still there. Any investigation path?

**Comment by GLD-NL** [comment]
Same problem here. I found out that it has something to do with special characters in a template. Like ' or á and characters like that. These characters are also a problem 阅读你的圣经,每天祈祷吧 I don't know if this is the real problem. But if I remove these kinds of characters, I can save the template.

It will be great if this can be fixed. 👍
