### ISSUE TITLE
500 Internal Server Error on landing page URL with tracking query string (?xxxxx) — device_tracking_service not found

### ISSUE THREAD

**Issue by AlexanderZlobinM1** [mautic/mautic#14955]
### Mautic Series

6.0.x series

### Mautic installed version

6.0.0.

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.3.20

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Description:

On a clean installation of the latest version of Mautic (tested on two different servers), accessing a landing page via an email campaign link that includes a tracking query string results in a 500 Internal Server Error. This appears to be caused by a missing service (mautic.lead.service.device_tracking_service) in the PublicController’s limited service container.

⸻

Steps to reproduce:
	1.	Create a landing page in Mautic.
	2.	Create an email that includes a link to the landing page.
	3.	Send the email as part of a campaign.
	4.	Click the link in the received email — Mautic appends a random query string like ?fasfasgfagnhdshb to the landing page URL.
	5.	The page fails to load and returns a 500 error.
	6.	Direct access to the same page without the query string works normally.

⸻

Expected result:

The landing page should load regardless of whether a query string is present.

⸻

Actual result:

A 500 error is thrown due to a missing service:

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: 
Service "mautic.lead.service.device_tracking_service" not found: even though it exists in the app's container, 
the container inside "Mautic\PageBundle\Controller\PublicController" is a smaller service locator 
that only knows about a limited set of services. 
Try using dependency injection instead.

This error happens consistently on different clean installations of Mautic on separate servers.

⸻

Related log entry:

Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: 
"Service 'mautic.lead.service.device_tracking_service' not found [...]" 
at /var/www/mautic/vendor/symfony/dependency-injection/ServiceLocator.php line 133

⸻

Environment:
	•	Mautic version: 6.0.0
	•	PHP version: 8.3.20
	•	MariaDB 11.4.5
	•	Server OS: Ubuntu 24.04

### How can we reproduce this issue?

	1.	Create a landing page in Mautic.
	2.	Create an email that includes a link to the landing page.
	3.	Send the email as part of a campaign.
	4.	Click the link in the received email — Mautic appends a random query string like ?fasfasgfagnhdshb to the landing page URL.
	5.	The page fails to load and returns a 500 error.
	6.	Direct access to the same page without the query string works normally.

### Relevant log output

```shell
[2025-04-29T15:55:02.379231+00:00] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "Service "mautic.lead.service.device_tracking_service" not found: even though it exists in the app's container, the container inside "Mautic\PageBundle\Controller\PublicController" is a smaller service locator that only knows about the "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer" and "twig" services. Try using dependency injection instead." at /var/www/mautic/vendor/symfony/dependency-injection/ServiceLocator.php line 133 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): Service \"mautic.lead.service.device_tracking_service\" not found: even though it exists in the app's container, the container inside \"Mautic\\PageBundle\\Controller\\PublicController\" is a smaller service locator that only knows about the \"form.factory\", \"http_kernel\", \"parameter_bag\", \"request_stack\", \"router\", \"security.authorization_checker\", \"security.csrf.token_manager\", \"security.token_storage\", \"serializer\" and \"twig\" services. Try using dependency injection instead. at /var/www/mautic/vendor/symfony/dependency-injection/ServiceLocator.php:133)"} {"hostname":"4588881-xd22841","pid":236232}
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by torton99** [comment]
This sounds similar to a hack I just added to my code. Perhaps this will help someone fix the issue properly, as this is just my temporary work-around to avoid the 500 error.

The issue is that Chrome creates a 15 second cookie that causes the get() below to critically fail. After the cookie expires the same page load no longer has the 500 error but we can't expect a user to wait 15 seconds to view the page.

I added a try/catch at approx line 301 of /app/bundles/PageBundle/Controller/PublicController.php

            if ($request->cookies->has('Blocked-Tracking')) {
                /* 25.04.28 Hack to prevent 500 error. */
                try {
                  if($this->container->has('mautic.lead.service.device_tracking_service')) {
                    /* @var DeviceTrackingService $deviceTrackingService */
                    $deviceTrackingService = $this->container->get('mautic.lead.service.device_tracking_service');
                    $deviceTrackingService->clearTrackingCookies();
                  }
                } catch(Exception $e) {
                  $this->logger->debug('Hack: trycatch fix used for Blocked-Tracking cookie.');
                }
            }

**Comment by AlexanderZlobinM1** [comment]
I will not take this approach since it only prevents the exception from occurring, and the functionality does not do what it is supposed to do.

I suggest injecting the service by adding DeviceTrackingServiceInterface $deviceTrackingService parameter to the \Mautic\PageBundle\Controller\PublicController::indexAction method. It should look like the following block code.
public function indexAction(
    DeviceTrackingServiceInterface $deviceTrackingService,
    Request $request,
    ContactRequestHelper $contactRequestHelper,
    CookieHelper $cookieHelper,
    AnalyticsHelper $analyticsHelper,
    AssetsHelper $assetsHelper,
    ThemeHelper $themeHelper,
    Tracking404Model $tracking404Model,
    RouterInterface $router,
    $slug)

Also, the 302 and 303 must be removed.
[PublicController.php.zip](https://github.com/user-attachments/files/19974604/PublicController.php.zip)

**Comment by AlexanderZlobinM1** [comment]
I put modified PublicController.php (see previous message) - It works for me

**Comment by datasolutionsbz** [comment]
I tried the modified PublicController.php  and got the below error:

mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Controller "Mautic\PageBundle\Controller\PublicController::indexAction" requires that you provide a value for the "$deviceTrackingService" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one." at /var/www/mautic/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 110 {"exception":"[object] (RuntimeException(code: 0): Controller \"Mautic\\PageBundle\\Controller\\PublicController::indexAction\" requires that you provide a value for the \"$deviceTrackingService\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one. at /var/www/mautic/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:110)"}

**Comment by AlexanderZlobinM1** [comment]
try to download file https://github.com/user-attachments/files/19974604/PublicController.php.zip

**Comment by datasolutionsbz** [comment]
I download the file  https://github.com/user-attachments/files/19974604/PublicController.php.zip and replace the php file in my instance. When i tested it go the error above.

**Comment by AlexanderZlobinM1** [comment]
try to clear cache after replace the file
bin/console cache:clear

**Comment by datasolutionsbz** [comment]
Yea, i tried clearing cache, I tried composer update, even rebooted the vm  etc ...

**Comment by AlexanderZlobinM1** [comment]
I use zip installation yet, I will try with composer.

**Comment by datasolutionsbz** [comment]
I had used git to deploy. I redeploy using the zip installation and applied your PublicController.php file. I can confirm that with the modified PublicController.php the error don't occur.

I look the the events for the contact i tested with. I am not seeing that a click event was triggered for the click tracking link...

**Comment by lippoliv** [comment]
I'm just starting with mautic, setting up a fresh 6.0.1 instance. I face this in my double-opt-in process

<img width="741" alt="Image" src="https://github.com/user-attachments/assets/85a0d20e-72f1-4c49-b144-42784fc622d8" />

(Following https://mautic.org/blog/creating-a-double-opt-in-email-campaign/)

When opening the mail and clicking the link, I see the error 500 page. 

```
[2025-05-22T00:43:45.760687+00:00] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "Service "mautic.lead.service.device_tracking_service" not found: even though it exists in the app's container, the container inside "Mautic\PageBundle\Controller\PublicController" is a smaller service locator that only knows about the "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer" and "twig" services. Try using dependency injection instead." at /www/htdocs/w0202340/reach.reliable.codes/vendor/symfony/dependency-injection/ServiceLocator.php line 133 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): Service \"mautic.lead.service.device_tracking_service\" not found: even though it exists in the app's container, the container inside \"Mautic\\PageBundle\\Controller\\PublicController\" is a smaller service locator that only knows about the \"form.factory\", \"http_kernel\", \"parameter_bag\", \"request_stack\", \"router\", \"security.authorization_checker\", \"security.csrf.token_manager\", \"security.token_storage\", \"serializer\" and \"twig\" services. Try using dependency injection instead. at /www/htdocs/w0202340/reach.reliable.codes/vendor/symfony/dependency-injection/ServiceLocator.php:133)"} {"hostname":"dd54720","pid":2125774}
```

Extending parameters of `\Mautic\PageBundle\Controller\PublicController::indexAction` didn't work for me (just got another error message complaining about missing `$deviceTrackingService`) but if I modify the condition above lines 302 & 303 to 

```php
            if (false && $request->cookies->has('Blocked-Tracking')) {
                /* @var DeviceTrackingService $deviceTrackingService */
                $deviceTrackingService = $this->container->get('mautic.lead.service.device_tracking_service');
                $deviceTrackingService->clearTrackingCookies();
            }
```

I don't get the error 500. But on the same site, my link click wasn't tracked either. So no double-opt-in.

**I found out: It is depending on the browser.** 
Using chrome on my Android 15 device, it works without any code modification. I can double-opt-in, all fine.
Using brave on my MacBook, with the same mail, I get ERR500. Sure, I can modify the code, but then I can't double-opt-in.

**Comment by npracht** [comment]
@kuzmany we see you changed the milestone of this issue. Are you considering working on it ?

**Comment by kuzmany** [comment]
@npracht no, I only move it outside of 6.0.2 what was closed

**Comment by shinde-rahul** [comment]
PR to test https://github.com/mautic/mautic/pull/15079.

**Comment by AlexanderZlobinM1** [comment]
> PR to test [#15079](https://github.com/mautic/mautic/pull/15079).
I am installed PublicController.php 

The 500 Error disappeared but I see following errors in the log.

[2025-06-08T20:54:52.299748+00:00] mautic.WARNING: PHP Warning - Attempt to read property "server" on null - in file /var/www/mautic/app/bundles/PageBundle/Helper/TrackingHelper.php - at line 126 [] {"hostname":"4588881-xd22841","pid":749}
[2025-06-08T20:54:52.299985+00:00] mautic.CRITICAL: Uncaught PHP Exception Error: "Call to a member function get() on null" at /var/www/mautic/app/bundles/PageBundle/Helper/TrackingHelper.php line 127 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /var/www/mautic/app/bundles/PageBundle/Helper/TrackingHelper.php:127)"} {"hostname":"4588881-xd22841","pid":749}
[2025-06-08T20:54:52.303501+00:00] mautic.CRITICAL: Exception thrown when handling an exception (Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Failed to start the session because headers have already been sent by "/var/www/mautic/vendor/symfony/http-foundation/Response.php" at line 408."). at /var/www/mautic/app/bundles/CoreBundle/Resources/views/Default/script.html.twig line 9) {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Failed to start the session because headers have already been sent by \"/var/www/mautic/vendor/symfony/http-foundation/Response.php\" at line 408.\"). at /var/www/mautic/app/bundles/CoreBundle/Resources/views/Default/script.html.twig:9)\n[previous exception] [object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/var/www/mautic/vendor/symfony/http-foundation/Response.php\" at line 408. at /var/www/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:132)"} {"hostname":"4588881-xd22841","pid":749}

**Comment by escopecz** [comment]
Heya, I fixed this bug here: https://github.com/mautic/mautic/pull/15102

Please give it a test so it can be merged soon.

**Comment by datasolutionsbz** [comment]
The 500 Internal Server Error on landing page is no longer showing. In testing i have the landing page with a click tracking button that makes a decision when click. In my testing it don't appear that the decision is being triggered when the button is click.

**Comment by lippoliv** [comment]
Thx @escopecz works for me. But the tracking still doesn't, depending on the browser. I create another bug for that.
