### ISSUE TITLE
7rc, We have detected 1 major problems. You must fix them before continuing - missing logs folder

### ISSUE THREAD

**Issue by BastianHammer** [mautic/mautic#15715]
### Mautic Series

7.0.x series

### Mautic installed version

7 rc

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.3

### What happened?

After composer installing my Mautic 7 environment, I pull up the browser and try to install / setup Mautic there.

I get:

<img width="1136" height="695" alt="Image" src="https://github.com/user-attachments/assets/4e3b2229-6869-42a6-a6f5-71b938795490" />

Permissions seem to be all in order, according to the docs.
Oddly enough, there is an odd character and now path / details about the issue pointed out.

After some digging, I found out, that the `var/logs` folder is missing.

So I've created it and now I see:

<img width="1136" height="517" alt="Image" src="https://github.com/user-attachments/assets/71515f12-157d-4a12-b79b-74ab4facee2a" />

Would probably be best, if the composer install could create the logs folder already.

Maybe it's related to my other install issues? But I had to do this on another environment as well, where the installation worked smoothly.
https://github.com/mautic/mautic/issues/15714

### How can we reproduce this issue?

Step 1: Composer install

### Relevant log output

```shell

```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by jos0405** [comment]
This is fixed as of general availability. I'f I'm mistaken, let me know and I reopen.

**Comment by BastianHammer** [comment]
@jos0405 
I just saw this one on the forums:
https://forum.mautic.org/t/mautic-7-installation-error-the-directory-must-be-writable-php-8-4-missing-var-logs-folder/37453
maybe not yet fixed? I'll check with the next 7.0.1

**Comment by BastianHammer** [comment]
Still had the same issue and method of resolution on a 7.0.1 install just now.
