### ISSUE TITLE
Search operator combine with search command is not working, example !list:name-list

### ISSUE THREAD

**Issue by rodrideme** [mautic/mautic#1593]
## Description

@escopecz and me tested combine search operator(!) with search command(list) to filter all leads out a specific list, didn´t work.
## Steps to reproduce

Insert !list:name-list in search lead

**Comment by escopecz** [comment]
(we also tried `list:!name-list`)

**Comment by ahansson89** [comment]
searching multiple emails also does not work.
"email1@example.com OR email2@example.com"

**Comment by alanhartless** [comment]
Both cases fixed in #2337

**Comment by ericgopak** [comment]
`OR` operator still does not work for me (v 2.2.1)
I tried:
`company:"company1" OR company:"company2"`
`company:company1 OR company:company2`
`company:"company1" OR "company2"`
`company:company1 OR company2`
`company1 OR company2`

What I mean by "does not work" is that the result is incorrect - only the search results of the first part (`company:company1`) are returned. So it seems like everything after `OR` is being ignored.
