### ISSUE TITLE
Mautic should use 'application/json' instead of 'application/x-www-form-urlencoded' for webhooks

### ISSUE THREAD

**Issue by lgfischer** [mautic/mautic#1782]
## Description

I'm trying to make a integration with Mautic using webhooks, but I am having problems with it.

I configured a Mautic instance to call a Webhook in my App everytime a contact is created. The problem is that Mautic uses the header "Content-Type: application/x-www-form-urlencoded; charset=utf-8" in the request that posts the JSON data into the Webhook. The "application/x-www-form-urlencoded" content type should be used to submit HTML forms (https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1). I'm not an expert in the HTTP protocol, but I believe that Mautic should use "application/json" content type when posting json data into webhooks.

I am reporting this because my app uses a framework that does a lot of things automatically based on the headers it receives from HTTP requests. Using the wrong content type causes my app to parse JSON data as if it was FORM data. I believe that improve on the usage of the HTTP protocol in this point can make easier to integrate Mautic with other apps.
## Steps to reproduce

1) Open the "Webhooks" page of a Mautic instance
2) Click "+ New" button to create a new Webhook
3) Open http://requestb.in/ and click "Create a RequestBin"
4) Copy the URL from the RequestBin site to the "Webhook POST Url" field in the new webhook page in Mautic
5) Click the "New Contact Event" checkbox and then on "Send test payload"
6) Refresh the RequestBin page

Current behavior:
- There is a header "Content-Type: application/x-www-form-urlencoded; charset=utf-8" in the RequestBin dump

Expected behavior:
- There should be a header "Content-Type: application/json; charset=utf-8" in the RequestBin dump
- The header "Content-Type: application/x-www-form-urlencoded; charset=utf-8" should not appear in the RequestBin dump

**Comment by dongilbert** [comment]
Fixed in #2318

**Comment by GabrielRoitman** [comment]
I'm still having this same issue 
![Captura de Pantalla 2019-09-08 a la(s) 17 59 29](https://user-images.githubusercontent.com/28110525/64494379-6d117780-d262-11e9-8f0e-8e02e87d41e2.png)

**Comment by escopecz** [comment]
@GaberNeighbor it's better to create a new issue rather than commenting on a closed one and a merged PR next time. It's a good idea to link the closed issue and the PR in the issue description. What Mautic version do you have?

**Comment by GabrielRoitman** [comment]
I'm on the latest version

**Comment by GabrielRoitman** [comment]
![image](https://user-images.githubusercontent.com/28110525/64607628-3db45500-d39f-11e9-9a99-08c77fbe77cc.png)

**Comment by escopecz** [comment]
The version number is in the bottom right corner of each Mautic page. What is it?

**Comment by GabrielRoitman** [comment]
v2.15.2

Thanks for the help!

**Comment by escopecz** [comment]
I cannot reproduce on 2.15.3:
![RequestBin - 18sg21h1](https://user-images.githubusercontent.com/1235442/64613438-6c99ed80-d3d6-11e9-8c30-e4a6e2e4b8b1.png)


Can you write step by step how you test it?

**Comment by GabrielRoitman** [comment]
I'm testing with requestbin.com:
![Captura de Pantalla 2019-09-10 a la(s) 10 38 12](https://user-images.githubusercontent.com/28110525/64618741-3bf68b80-d3b7-11e9-9792-27fde7f4f94a.png)
This is what I'm getting:
![Captura de Pantalla 2019-09-10 a la(s) 10 38 23](https://user-images.githubusercontent.com/28110525/64618781-49ac1100-d3b7-11e9-91b7-d6d7287bf1d7.png)

**Comment by escopecz** [comment]
Oh, you are talking about campaign webhooks. This issue is about global webhooks. Create a new issue, please.
