### ISSUE TITLE
release-2.0.0: 500 Internal Server Error when trying to add a new form etc.

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#1953]
Just upgraded from 1.4.1 to 2.0.0 (via the web interface).
Deleted the contents of the cache folder after update. 

When trying to add a new form (or assets, landing pages, dynamic content) I'm getting 500 Internal Server Errors.
So, unable to add forms, assets, landing pages after update. 
Before update everything seemed to work fine and there were no errors in Chrome inspector either.

The Chrome inspector shows this: 
`http://www.mydomain.com/e/s/ajax?action=commandList&model=dwc&_=1467738706647&mauticUserLastActive=1&mauticLastNotificationId=24 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.mydomain.com/e/s/dwc/new?_=1467738706648&mauticUserLastActive=1&mauticLastNotificationId=24 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.mydomain.com/e/s/assets/new?_=1467738706657&mauticUserLastActive=1&mauticLastNotificationId=24 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.mydomain.com/e/s/ajax?action=commandList&model=dwc&_=1467738706659&mauticUserLastActive=1&mauticLastNotificationId=24 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.mydomain.com/e/s/dwc/new?_=1467738706660&mauticUserLastActive=1&mauticLastNotificationId=24 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.mydomain.com/e/s/forms/new?_=1467738706662&mauticUserLastActive=1&mauticLastNotificationId=24 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
libraries.js?v2.0.0:4819 Uncaught TypeError: Cannot read property 'x' of undefined`

**Comment by abooster** [comment]
P.S. 
This same "500 Internal Server Error" comes up when clicking ANY button that says "+ New".
So, it's not just forms and assets. It's also campaigns and everything else.

**Comment by escopecz** [comment]
Please post here the error logs recorded in the app/logs directory and in the server error log.

**Comment by abooster** [comment]
There are currently just 2 files in the logs folder:
mautic_prod-2016-07-05.php
prod-2016-07-05.php

Not sure which contains the logs.

**Comment by abooster** [comment]
Here are the contents of mautic_prod-2016-07-05.php:
[2016-07-05 17:11:16] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /home/REPLACED/public_html/e/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []
[2016-07-05 17:12:09] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.dwc.model.dwc is not a registered container key." at /home/REPLACED/public_html/e/app/bundles/CoreBundle/Controller/CommonController.php line 120 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.dwc.model.dwc is not a registered container key. at /home/REPLACED/public_html/e/app/bundles/CoreBundle/Controller/CommonController.php:120)"} []
[2016-07-05 17:12:13] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:16:21] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /home/REPLACED/public_html/e/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []
[2016-07-05 17:20:23] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:20:27] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.dwc.model.dwc is not a registered container key." at /home/REPLACED/public_html/e/app/bundles/CoreBundle/Controller/CommonController.php line 120 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.dwc.model.dwc is not a registered container key. at /home/REPLACED/public_html/e/app/bundles/CoreBundle/Controller/CommonController.php:120)"} []
[2016-07-05 17:20:30] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:20:36] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:33:51] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:34:15] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:34:28] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.dwc.model.dwc is not a registered container key." at /home/REPLACED/public_html/e/app/bundles/CoreBundle/Controller/CommonController.php line 120 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.dwc.model.dwc is not a registered container key. at /home/REPLACED/public_html/e/app/bundles/CoreBundle/Controller/CommonController.php:120)"} []
[2016-07-05 17:34:29] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:38:01] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:38:11] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:38:22] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []
[2016-07-05 17:39:36] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []

**Comment by escopecz** [comment]
> There is no suitable CSPRNG installed on your system

I don't have time to search deeper, but it seems some PHP library is outdated. Probably Mcrypt or Curl. Feel free to search for this error message yourself. To resolve it, contact your server admin. He should know how to deal with it. And let us know what was it in your case, please.

**Comment by abooster** [comment]
In the server error logs I found the following relevant info:

[Tue Jul 05 13:10:50.110316 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqGc8HVkEAAAhCrg4AAAAL"]
[Tue Jul 05 13:10:51.448236 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqGs8HVkEAAAhCrg8AAAAL"]
[Tue Jul 05 13:10:52.000388 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqG88HVkEAAAhCrhAAAAAL"]
[Tue Jul 05 13:10:52.853998 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqHM8HVkEAAAhCrhEAAAAL"]
[Tue Jul 05 13:10:53.794415 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqHc8HVkEAAAhCrhIAAAAL"]
[Tue Jul 05 13:10:55.769627 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqHc8HVkEAAAhCrhMAAAAL"]
[Tue Jul 05 13:10:56.966619 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqH88HVkEAAAhCrhQAAAAL"]
[Tue Jul 05 13:10:58.316650 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqIc8HVkEAAAhCrhUAAAAL"]
[Tue Jul 05 13:10:59.235580 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqIs8HVkEAAAhCrhYAAAAL"]
[Tue Jul 05 13:10:59.479666 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqI88HVkEAAAhCrhcAAAAL"]
[Tue Jul 05 13:10:59.851683 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqI88HVkEAAAhCrhgAAAAL"]
[Tue Jul 05 13:11:03.155665 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqJM8HVkEAAAhCrhkAAAAL"]
[Tue Jul 05 13:11:08.411404 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: Rule 3f4e3d8 [id "220111"][file "/usr/local/apache/conf/modsec_vendor_configs/comodo_apache/32_Apps_OtherApps.conf"][line "45"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.mydomain.com"] [uri "/e/upgrade/upgrade.php"] [unique_id "V3vqJ88HVkEAAAhCrhoAAAAL"]
[Tue Jul 05 13:39:33.805894 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: collections_remove_stale: Failed to access DBM file "/var/cpanel/secdatadir/global": Permission denied [hostname "www.mydomain.com"] [uri "/e/index.php"] [unique_id "V3vw1c8HVkEAAAhCrioAAAAL"]
[Tue Jul 05 13:39:33.805964 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: collections_remove_stale: Failed to access DBM file "/var/cpanel/secdatadir/ip": Permission denied [hostname "www.mydomain.com"] [uri "/e/index.php"] [unique_id "V3vw1c8HVkEAAAhCrioAAAAL"]
[Tue Jul 05 13:39:33.806010 2016] [:error] [pid 2114] [client 95.91.225.180] ModSecurity: collections_remove_stale: Failed to access DBM file "/var/cpanel/secdatadir/default_SESSION": Permission denied [hostname "www.mydomain.com"] [uri "/e/index.php"] [unique_id "V3vw1c8HVkEAAAhCrioAAAAL"]

**Comment by abooster** [comment]
Where can I download 2.0.0 for a fresh install?

**Comment by escopecz** [comment]
https://mautic.org/download . I'll close this issue then. If you get the same errors with the new install, please, contact your server admin.

**Comment by maartenroelofs** [comment]
just to add to this; similar error found in logfiles here; 


[2016-07-11 19:23:57] mautic.CRITICAL: Uncaught PHP Exception BadMethodCallException: "Undefined method 'getDwellTimesForUrls'. The method name must start with either findBy or findOneBy!" at /home/admincrmdepascor/public_html/mm.mautic.marketing/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php line 226 {"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'getDwellTimesForUrls'. The method name must start with either findBy or findOneBy! at /home/admincrmdepascor/public_html/mm.mautic.marketing/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:226)"} []
[2016-07-11 19:55:06] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.dwc.model.dwc is not a registered container key." at /home/admincrmdepascor/public_html/mm.mautic.marketing/app/bundles/CoreBundle/Controller/CommonController.php line 120 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.dwc.model.dwc is not a registered container key. at /home/admincrmdepascor/public_html/mm.mautic.marketing/app/bundles/CoreBundle/Controller/CommonController.php:120)"} []

**Comment by escopecz** [comment]
@maartenroelofs this error was already fixed and the fix should be released in 2.0.1 today.

**Comment by ivent** [comment]
Interesting I am seeing this text in 2018 and in version v2.13.1 there are still the same problems after all this has already been solved? I am a week trying to install the mautic and solving having to solve more than 4 bugs to see if it works sinceramete what for me seemed the solution of my problems already caused more problems than expected.
