### ISSUE TITLE
Custom theme install requires config.json in top level. 

### ISSUE THREAD

**Issue by lightweight** [mautic/mautic#2287]
Bug report

## Description:
Cannot install a theme unless the config.json file is in the *top* level of the zip file hierarchy. This disallows making a zip file of a theme directory and seems inconsistent with default stock themes.

## If a bug:
Mautic version - 2.1.0 (using Mautic.net, i.e. reference instance)

### Steps to reproduce:
1. create a theme as per Mautic 2.1.0 custom theme video 
1. zip directory, e.g. theme (containing valid config.json, css, html, img dirs, and thumbnail.png) into theme.zip 
1. select file on /s/themes and click "Install" (this, button, by the way, is sometimes greyed out/disabled on Firefox 47 on Linux - a full reload of the page seems to make it active again)
1. get error "The theme you tried to install doesn't have the config.json file in the root folder. The theme could not be installed"

I note that the downloadable stock themes (e.g. Skyline) are all buried in deep directories (e.g. usr/local/share/mautic/production/releases/20160811064208/themes/skyline).

**Comment by escopecz** [comment]
I don't get what is the bug in it? If you make a zip file, you zip the whole file system of your computer? I wrote [the dev docs](https://github.com/mautic/developer-documentation/pull/20/files) for zip file structure, but they weren't merged to production yet.

So basically, you develop your theme lets say in 

`usr/local/share/mautic/production/releases/20160811064208/themes/skyline2`

directory. Then you open to that `skyline2` directory, select all files and folders in it, right click on them and select the "Compress" item in the context menu. Every OS calls it differently, but I believe every OS provides it by default or in case of Windows, you have to install the WinRar program.

Or am I missing something?

**Comment by lightweight** [comment]
Thanks for the response. The path I included (that you cited) is the one that I get when I download the current Skyline theme from Mautic.net (or our paid sub-site). If I try to upload a theme where the required files are not in the top directory of the zip archive, then I get the error about "no config.json found in the top level directory"... Seems like it'd be better if the import script searched for a config.json file in the zip archive and then looked for the other relevant file in *that* directory. In my opinion, it's good practice to have archives inside a directory, rather than a loose collection of files in the top level (because it's hard to clean up if you unzip it in the wrong place by accident)... Hope that makes sense. I'm using Linux for development, for the record.

**Comment by escopecz** [comment]
Ok, I tested it on mautic.net and now I know what are you talking about with the directories. It's a bug specific to mautic.net though. I'll report it there.

We spoke about this when developing the theme manager and we decided to keep it simple. I'll mark this as a feature request and we'll see how many people will have trouble with the zip file structure.

**Comment by dongilbert** [comment]
Fixed in #2297

**Comment by shaunpalmer** [comment]
Is definitely something kinky going on here it may not be a bug but it's a definite annoyance it means that I can't actually get them the zip file into the ready to be a theme

**Comment by mayanktiwaridotcom** [comment]
Something is still not right, I created a simple form theme and right click on directory to zip it and it won't accept for installation. 
I had to go inside and select all directories in order to get it zipped, even then after installation it totally ignored the html/MauticFomBunlde/ directory.

**Comment by escopecz** [comment]
> after installation it totally ignored the html/MauticFomBunlde/ directory

I discussed this with a friend this week. The bundle template overrides does not work with twig as the originals are in PHP. And the theme installer removes all PHP files for security reasons. So the only way how to make the bundle template overrides work is to install the theme by copy-pasting the theme to the themes folder directly. Do not use an installer.

It's obviously a bug, but it will be hard to solve without rewriting all PHP template files to twig.
