### ISSUE TITLE
UI problem when configuring actions in negative cases in campaigns

### ISSUE THREAD

**Issue by insetic** [mautic/mautic#2396]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

Due that there is a new behavior when configuring an action in negative cases, **it is scheduled by default to trigger within a day**.

When you try to add a Dynamic Web Content action, there is no possibility to configure when to execute the event, but by default it is scheduled to trigger within a day, which it's a problem. 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.24 |
### Steps to reproduce:
1. In a campaign, add a Decision step that Request a Dynamic Content
2. Add a Condition based in a Contact Field Value
3. Add a negative Action that Push a Dynamic Content

![image](https://cloud.githubusercontent.com/assets/20638806/17980895/a48b52ce-6b01-11e6-967d-8ff0472f5f79.png)
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Mazzim** [comment]
I can confirm this, I see the same behavior. Mastic 2.1.1, PHP5.6.23

**Comment by dongilbert** [comment]
There shouldn't be a time to schedule the action for Dynamic Content, because they are requesting at that moment and need the values. Scheduling it out just wouldn't work. However, it should default to immediately instead of in 1 day. Definitely a bug.

**Comment by alanhartless** [comment]
Yea this came about as a result of the campaign redesign and obviously not
intended. I'll be looking at this shortly. Just need to add immediate back
as an option for "false" conditions.

**Comment by alanhartless** [comment]
#2423 should now fix this.

**Comment by insetic** [comment]
Hi, this problem persists in v2.2.0

Also I've tried to apply again #2423 but without success.

![image](https://cloud.githubusercontent.com/assets/20638806/19212573/4123ad7e-8d54-11e6-9a06-d0b947e53cf6.png)

**Comment by mqueme** [comment]
This has been fixed in 2.7.0. Can you please confirm that this is no longer happening in version 2.7.0
