### ISSUE TITLE
Tag search does not work

### ISSUE THREAD

**Issue by meggiebbq** [mautic/mautic#2512]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No 
| Enhancement? | No

## Description:
My campaign adds tags to my contacts whenever they do an action. When I want to filter the contact list by tag, I see the command in the search bar: "tag:" But whatever tag I write, Mautic returns no result.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | revision 5c8b5d6
| PHP version | 5.6.23

### Steps to reproduce:
1. Add a tag to some of your contacts
2. Go to your contact list
3. Start typing "tag" in the search bar: you'll see the command "tag:"
4. Write the name of the tag you are searching for and press enter
5. Mautic returns no results, eventhough you do have contacts with this tag.
 
### Log errors: 

No related log errors

**Comment by alanhartless** [comment]
Fixed in #2559

**Comment by redcage** [comment]
I've just tested it on my cloud mautic and it's still not working.

**Comment by that0n3guy** [comment]
@redcage Fixed on a different issue/PR doesn't mean its been deployed to mautic.com.
