### ISSUE TITLE
Unable to auto-tweet using mautic campaign

### ISSUE THREAD

**Issue by amarjeetsharma** [mautic/mautic#2789]
What type of report is this: Bug Report

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

We are monitoring Brand Mentions in Twitter and updating them to a segment. 
Using a simple campaign :
Step 1 : Selecting Segment
Step 2: Auto-tweet "{twitter_handle} Thank you for mentioning us amongst your followers."

![image](https://cloud.githubusercontent.com/assets/22935042/19517609/e9c57862-961f-11e6-970c-9e95e03b2364.png)
## If a bug:
1. Monitoring : Success
2. Segment Updation : Success
3. Auto-tweets : **Failure**

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.26 |
### Steps to reproduce:
1. Configure Twitter Plugin and Authorize
2. Create a Segment 
3. Select Channels >> Social Monitoring >> Create New >> Monitoring Method : Twitter Mentions
4. Input Twitter Handle to monitor >> Add contact to selected Segment
5. Create Campaign >> Select Segment >> Auto Tweet
### Log errors:

Can't decipher if this log is relevant but it's all there is 
[2016-10-19 08:24:51] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #37. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object](Doctrine\ORM\ORMInvalidArgumentException%28code: 0%29: A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #37. To solve this issue: Either explicitly call EntityManager#persist%28) on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
[2016-10-19 08:27:27] mautic.WARNING: IP LOOKUP: The file "/var/www/html/mautic/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2016-10-19 08:27:28] mautic.WARNING: IP LOOKUP: The file "/var/www/html/mautic/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you please double-check that you have Mautic 2.2.1 and the upgrade was without any hiccups? Because very similar error was fixed in 2.2.1.

**Comment by amarjeetsharma** [comment]
Rechecked the version still not working. I've reinstalled the v2.2.1 and was without any hiccups but issue remains.

**Comment by fixmyinfo** [comment]
Latest version of everything here - same issue - it says it is tweeting but I see no tweets. The social profiles are mostly properly attached, so I know the integration is somewhat functional.

**Comment by fixmyinfo** [comment]
Anything to do here? Still not working...  :(

**Comment by MxyzptlkFishStix** [comment]
Have you added the mautic:social:monitoring cronjob?

**Comment by fixmyinfo** [comment]
Hi yes - the monitoring is working properly with the cron - it is not *sending* tweets as expected/directed in a campaign though.

**Comment by npracht** [comment]
Same issue here, the tweet never leaves.

**Comment by fixmyinfo** [comment]
If there is anything more tha I can provide, I would love to - please advise...

**Comment by 3ruce** [comment]
Ok, I am also having this problem.. below is output from the command line when I run 

/usr/bin/php /home/admin/public_html/app/console mautic:campaigns:trigger

```
Triggering events for campaign 27
Triggering first level events
92 total events(s) to be processed in batches of 100
  0/92 [>---------------------------]   0%PHP Notice:  unserialize(): Error at offset 172 of 262 bytes in /home/admin/web/get.brandreflections.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58
 92/92 [============================] 100%
92 event(s) executed
```

Everything is up to date with the installation...

Does anyone have any ideas? Thanks...

**Comment by IADDIC** [comment]
@3ruce @npracht @fixmyinfo @MxyzptlkFishStix @escopecz 

I was chasing this issue to ground along with a host of other social integration problems (see [3556](https://github.com/mautic/mautic/issues/3556)) and discovered twitter not auto posting was caused by a block imposed by twitter.  I recommend you visit your developer page.  If twitter is blocking you there will be a huge red message:   

![image](https://cloud.githubusercontent.com/assets/4072655/23525981/012f6f72-ff56-11e6-9018-5774eb133e0d.png)

 Mautic does not report the error, you must go to your twitter developer account.

Hope this helps someone!

**Comment by fixmyinfo** [comment]
@IADDIC - THANK YOU!  Yes, I was blocked here too and did not see it. Now it is on a new app - let's hope it sticks. THANKS again. :)

@3ruce @npracht @fixmyinfo @MxyzptlkFishStix @escopecz

**Comment by 3ruce** [comment]
Intriguingly my app wasn't blocked, it was setup fresh yesterday on a twitter account I also setup yesterday that had just sent a single 'my first tweet' tweet...

**Comment by IADDIC** [comment]
@fixmyinfo I do not know of a way to throttle the sending of tweets, so the number of tweets is directly related to the number hits that are returned from your search.  So, if you get a large number of return hits Mautic will send a large number of tweets and chances are your app will be suspended again.  

This is really a bug...enhancement...I am not sure how to clasify it because it is useless as it stands.

**Comment by escopecz** [comment]
The Tweet code was rewritten here: https://github.com/mautic/mautic/pull/3748 and it sends tweets while I was testing it. Feel free to give it a test.

The `unserialize` error is not directly related to tweets and it's reported in another issue. #3748 does not fix that.
