### ISSUE TITLE
Emails with Attachments get sent without attachment attached.

### ISSUE THREAD

**Issue by Loanatik** [mautic/mautic#3064]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by pavel-janicek** [comment]
Issue can be also reproduced on version 2.2.1

**Comment by jobberwalker** [comment]
Hello,

The same issue on v2.5.1, the emails are sent without attachment.

Best Regards
JB

**Comment by Loanatik** [comment]
This is a problem for me too.

**Comment by merlin0** [comment]
For me this is fixed in 2.7.0

**Comment by virlatinus** [comment]
For me it is also fixed in 2.7

**Comment by rtg20** [comment]
Hi, I have v2.7.0 and it is not fixed for me. Please help. thank you!

**Comment by nms** [comment]
This is not fixed for me. Using 2.8.0 and Sparkpost

**Comment by calevans** [comment]
I am experience the same problem. My attachment is a remote attachment from S3.

Mautic: 2.8.1
PHP: 7.1.4
ESP: Mailgun 

Checking the Mailgun logs, there is no attachment listed.

Checking the Mautic logs, no error is reported.

Cheers! :)
=C=

**Comment by calevans** [comment]
Update. 

My issue seems to be with S3. A local attachment works fine. 

Cheers! :)
=C=

**Comment by YannickBiet** [comment]
Mautic 2.8.2 sending email using send mail button on contact. Use a template (with attachment) received the email body but without any attachment 

it works fine if i am pressing "send example" button from the email detailview but not when sending from the contact / contact list....

**Comment by escopecz** [comment]
Please create a new issue. It's a bit different than this closed one.

**Comment by cschwartz85032** [comment]
I'm still having this issue in 2.11

**Comment by Bizcrony** [comment]
@cschwartz85032 are you sure that assets is attached properly. Did you try with test mail.
