### ISSUE TITLE
Save and Close button doesn't save or not working in confiugration.

### ISSUE THREAD

**Issue by ttmubarak** [mautic/mautic#3258]
Bug report:

Mautic version : 2.5.1 
php version     : php7.0

Save and close button doesn't work properly, or it doesn't save after clicking the save and close button. In configuration option. Please check and update the correct the problem.

**Comment by jordan8037310** [comment]
Confirmed for Reports in Mautic 2.4.0

**Comment by ttmubarak** [comment]
Please tell us, how to resolve that in 2.5.1

**Comment by PeteOliveira** [comment]
I am having the same issue on 2.5.1.  Trying to add CORS settings "valid domains"
Tried adding a single domain, click Apply, no errors but not saved.
Tried adding a single domain, click Save and Close, no errors, not saved.

2 sites running 2.5.1 are having the same problem.
2 site running 2.4.0 work fine

**Workaround:**

1. Fill in the required fields for SAML SSO Settings
2. Apply or Save
3. Make other changes and Save, it should now work

**Comment by ttmubarak** [comment]
Hi, Finally I cleared the problem on configuration save & close. By doing manually in local.php file.

**Comment by PeteOliveira** [comment]
@ttmubarak try my workaround if you need to save more settings.
Should work, I had 2 sites with the issue and it worked for both.

**Comment by ttmubarak** [comment]
@PeteOliveira  I didn't get that workaround , how do you change   SAML SSO settings, Please explain , I didn't get that

**Comment by Arjoni** [comment]
Just write something random.

**Comment by PeteOliveira** [comment]
@ttmubarak I have updated the comment with additional steps.
Please post if workaround works for you as it may help developer fix the issue.

**Comment by ttmubarak** [comment]
@PeteOliveira  I am very sorry to understand your steps, related to this. I can change via local.php file. By manually adding data to them. /app/config/local.php

**Comment by PeteOliveira** [comment]
-- 
Pete Oliveira

**Comment by PeteOliveira** [comment]
@ttmubarak see if this helps

![configuration___mautic](https://cloud.githubusercontent.com/assets/676739/22097847/7f6df9cc-dde0-11e6-8564-69ca58bbfa3a.png)

**Comment by ttmubarak** [comment]
@PeteOliveira , Its a big solution, Thank you great work

**Comment by MxyzptlkFishStix** [comment]
I gave you the solution over [here](https://github.com/mautic/mautic/issues/3248#issuecomment-273060657).

**Comment by npracht** [comment]
# Reason of the issue
**@escopecz it's clearer here.**
The issue happens when you try to save configuration and when SAML SSO is not configured because some fields are required as explained here: https://github.com/mautic/mautic/issues/3258#issuecomment-273703532

Many people does not have SAML SSO configuration and the conclusion is that thy cannot save (or they have to add a fake value in SAML SSO).

N.

**Comment by escopecz** [comment]
This was fixed in 2.6.0

**Comment by brian8888** [comment]
Hi, i have the same problem. I follow the advice in this thread to fill up and save "SAML SSO settings" (as posted by @petebytes 

I am still unable to save the email setting's password

![mautic cannot save password - 01](https://user-images.githubusercontent.com/36063996/35718300-cae0521a-081e-11e8-98e9-9d00f969d931.png)

![mautic cannot save password - 02](https://user-images.githubusercontent.com/36063996/35718301-cb1fa488-081e-11e8-9ccb-1ca1b46499c3.png)

**Comment by Bizcrony** [comment]
Clear cache .. its seem your server issue ,.

**Comment by brian8888** [comment]
@bizcrony Hi, i just clear the cache but still unable to save

I clear the cache here : cPanel > File Manager > My Mautic folder > App > Deleted the whole Cache folder

**Comment by Bizcrony** [comment]
Yes ///

**Comment by Bizcrony** [comment]
PM i will fix if still you have problem

**Comment by Bizcrony** [comment]
I misunderstood ... your password has been saved .. don't worry .. you may proceed , just check test connection .. it would work

**Comment by brian8888** [comment]
Thx it is working although that column is still empty. Thx again @Bizcrony

**Comment by Bizcrony** [comment]
@cStuartHardwick inspect and see the there will be 403 forbidden issue , that is of course  an issue with server not with mautic.

**Comment by cStuartHardwick** [comment]
Thanks, that seems unlikely. 
I've been using Mautic for 2 years. Permissions have not changed. CPanel errors under metrics is empty. Where would I look for the 403 error?

**Comment by cStuartHardwick** [comment]
Also, I can create and save other objects, just not emails.

**Comment by cStuartHardwick** [comment]
@Bizcrony have you any idea how I should proceed on this? You were correct that it's a 403 error, but without knowing what Mautic is attempting to access that's being denied, that's roughly equivalent to knowing "s'broke."

The error only appears in the IE debugger, and it's the exact text I pasted above. It's not logged on the server anywhere that I can find. I understand that the error is coming from the server, but I have no clues to follow. I even tried taking a capture, but all that told me is that there's a surprising amount of TCP traffic in between the POST and the 403--in other words, nothing.

Thanks.

**Comment by cStuartHardwick** [comment]
This has been resolved by having Namecheap disable modsecurity. That seems like an extreme solution, but they kept coming back to it.

**Comment by mediamix-NJ** [comment]
I host my own sites on an Ubuntu 16.04 server.
I have 3 websites with the latest version of Mautic running on each.

All worked until I needed to change the IP address on the server.
Now 2 of the Mautic installs still work but the third has the problem described in this post

When I enter Configuration and then click either apply or Save and exit, I get Please Wait...
Nothing happens until I click the back button on the browser.
Changes are not saved.

On the working Mautics, when I exit and save a box appears at the bottom of the browser that displays "waiting for www.xxxxxx.com"

On the non-working Mautic, that box does not appear.

Any idea how to fix this?

Thanks

**Comment by bennywaters** [comment]
I spent two full weeks chasing this issue. New dedicated server. Multiple different Mautic releases. Tied everything. Searched everything. Enabled disabled every known configuration, including mod_sec.
Resolution for me came by chance - reading about Cors, the issue was being caused by my wordpress installation and installed security plugin, Wordfence in the top level account being overbearing on the sub domain installations. Who would have thought? We see no errors in any Apache or mod_sec logs. It drove us nuts. 
As the function below which was getting the 403 as it uses CSRF (Cross Site Request Forgery), Which abuses the trust relationship between the browser and the server, Wordfence stops CSRF and XSS attacks.
I am not sure why the system is designed to use CSRF in this feature, So With Wordfence being installed in the top level account any of the sub folders that are using CSRF or XSS is being covered by WordFenses overbearing Security and is instantly giving a 403 WITHOUT any error messages given. Hope this has helped someone. Thanks to everyone who offered suggestions.
