### ISSUE TITLE
Error: DynamicContentBundle has no field or association named title

### ISSUE THREAD

**Issue by dirtroof** [mautic/mautic#4236]
| Bug report? | 

## Description:
Ran into this odd, hopefully, easy to fix bug. From the Mautic front-end log:
`mautic.ERROR: Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 168 near 'title DESC': Error: Class Mautic\DynamicContentBundle\Entity\DynamicContent has no field or association named title - in file public/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php - at line 63 [] []`

## If a bug:
| Mautic version | 
2.8.1

| PHP version | 
7.0.20

### Steps to reproduce:
1. Click Components—>Dynamic Content
2. Click the "Title" sorting order link at the top of the list

**Comment by escopecz** [comment]
Thanks for the report! Fixed in #4237, ready to test.

**Comment by dirtroof** [comment]
Updated to 2.8.2 from 2.8.1 (no problems btw, via the update button, thanks!)

Still have the issue. Logout/login fixes it fortunately.
