### ISSUE TITLE
Form broken if using modify contatc's segments or contact's tags

### ISSUE THREAD

**Issue by Schokolader** [mautic/mautic#4520]
| Bug report? | 

## Description:
If you use in a campaign modify contact's tags or modify contact's segments 
then the form is not working correctly.  Submit button keeps in "please wait forever"
https://www.mautic.org/community/index.php//8112-forms-not-working

## If a bug:
Mautic 2.9 
PHP 7.0
### Steps to reproduce:
1.  Use Modify contact's tag or modify contac'ts segments in a campaign
2.  Integrate a mautic form on your website 
3. Press submit button 
4. The form will not work. Submit button keeps in "please wait forever"

**Comment by escopecz** [comment]
Should be fixed on 2.9.2. Please retest and let us know.

**Comment by derrickgupta** [comment]
Escopecz, this form issue is still coming in v2.9. can you please update?

**Comment by escopecz** [comment]
Wait, what is the third number of the version you tested with?

**Comment by derrickgupta** [comment]
I am using v2.9.2. what do you mean by the third number of the version?

**Comment by escopecz** [comment]
You provided only "2.9" instead of "2.9.2". I was curious about the third number since that was the original question.

**Comment by escopecz** [comment]
Please retest with 2.14.2. There were many changes since then. I cannot replicate.
