### ISSUE TITLE
Form submitting error 500

### ISSUE THREAD

**Issue by Schokolader** [mautic/mautic#4726]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When you sign up with the mautic form than you will get a 500 Internal Server Error " Uh oh! I think I broke it. If I do it again, please report me to the system administrator! "  
Then if you hit the "back" button of your web browser and click again to submit your form it works. 
But always the first time you get a 500 Internal Server Error. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0

### Steps to reproduce:
1. Create a form and add it to your website
2. Create a campaign that modifies the segments of a contact
3. Create a campaign for the new segments contacts for sending mails
4. Fill out the form on your website and click submit 
5. The first time you get the error 
6. if you go back and click again submit then it works 
 
### Log errors: 

[2017-08-25 10:16:32] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #481. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #481. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by escopecz** [comment]
I cannot replicate.

1. Is it a standalone form or a campaign form? The error message is related to campaigns, but your steps suggests it's a standalone form. In that case the error message won't be related to your steps.

2. Do you get that when logged in to Mautic in the same browser and/or in incognito browser window?

**Comment by Schokolader** [comment]
The 500 error is gone now. It shows just "please wait..." now. 

1. it is a campaign form. The steps are similar to the honey pot method. https://www.mautic.org/community-blog/eliminate-spambots-using-the-honeypot-method/

2. yes "please wait..." with and without incognito mode

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4656. Please test the suggested change

**Comment by Schokolader** [comment]
on 2.10.1 no change. I still have after the form submit "Please wait..."

**Comment by npracht** [comment]
Hi @Schokolader do you still have this issue on 2.14.1 ?
Also, could you share new logs or browser console error ?

Thanks
