### ISSUE TITLE
Scheduled segment emails

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#574]
Let's add the option to schedule a list email to be sent.  This will probably require another cronjob.

**Comment by pitus** [comment]
Why not just use a Campaign with a specific Date as delay to trigger mailing at a specific date/time?

**Comment by zbabyface** [comment]
Was just looking for this feature.  What's an eta on adding this feature?

**Comment by ahansson89** [comment]
+1 I would like to send x number of emails from a list every day until all leads have been emailed.

**Comment by that0n3guy** [comment]
> +1 I would like to send x number of emails from a list every day until all leads have been emailed.

@ahansson89 This seems like a mail server config thing, not a mautic thing to me...   Sounds like you want to limit your send speed.

**Comment by ahansson89** [comment]
I disagree. If I limit it in the server config, then I will not be able to send to multiple lists or campaigns. What I want to do is to send 1000 emails per day to a specific list, then maybe I want to send 20,000 emails as part of a campaign later.

**Comment by that0n3guy** [comment]
Ok, I can see that, but what is the use-case of only sending to some of a list every day?  I don't know of any service that does that.

**Comment by ahansson89** [comment]
We have a small sales and marketing team. Sending out emails to 10,000 leads at once may be too much to handle. If we send it out in batches of 1,000 per day, then our team will be able to handle it.

**Comment by that0n3guy** [comment]
Gotcha.  Definitely valid for your business, but I'm not sure that's a "core" thing since its very specific to you.  Personally, I'd say that's a sales issue, not a tech issue :) (a good issue to have I guess, ha).  I'll keep out of this one and let Alan take it from here.

**Comment by ps92** [comment]
@pitus @alanhartless There is a something wrong that does not allow you to send variants to the leads in a campaign. For now, the only way to have a A/B email campaign is to send emails through List Email. 

So, I think this feature of scheduling a campaign might be necessary.

**Comment by rodrideme** [comment]
In the mautic.com is possible schedule email list :)

**Comment by vegasmi** [comment]
@allyde @alanhartless Why are there differences in features of the mautic.com and mautic bundle>

**Comment by alanhartless** [comment]
Fixed with #2259

**Comment by maxitromer** [comment]
+1 +1 +1

This is an important feature if you have a big segment and need to send an email to all.

In the current version if you need to send an email like this you have to be there in the moment you want to send the email and click send. 

And if your segment is big you need to wait (sometime for hours) until all the emails are send. 

It's ok if we need to add a new cronjob, the idea is to solve this ASAP.

I'm not a coder but if I can help here I am.

Thanks.

**Comment by StoppingBuck** [comment]
Hi, why was this closed? AFAICS this is still not an option?

**Comment by escopecz** [comment]
@StoppingBuck It's implemented. Here are the docs: https://mautic.org/docs/en/setup/cron_jobs.html#send-scheduled-broadcasts-e-g-segment-emails
