### ISSUE TITLE
Elastic Email bounce notification url returning an error on setup

### ISSUE THREAD

**Issue by RafaelLVX** [mautic/mautic#6250]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | n
| Enhancement? | n

## Description:
First timer, self hosted Mautic install on Cloudways/Digital Ocean. I set up Elastic Email, sending mail fine. To get bounce notifications I follow these instructions: https://www.mautic.org/docs/en/emails/bounce_management.html#elastic-email-webhook. So I log into Elastic Email, go to Settings -> Notification > HTTP Web > Notification URL and set it to http://my-mautic-url/mailer/elasticemail/callback. Then I check Unsubscribed, Complaints, Bounce/Error and click on save. I get three types of errors depending on time of day, but they all seem to sum up to an internal server error.

Varying errors:

"HTTP Web Notifications URL couldn't be validated. The remote server returned an error: (500) Internal Server Error." <-- this one always appears if I use https.
"Provided HTTP Web Notifications URL http://mauticurl/mailer/elasticemail/callback doesn't return valid HTTP Status Code (200)."
"HTTP Web Notifications URL couldn't be validated. The request was aborted: The connection was closed unexpectedly."

So it doesn't save my setting.

Out of options, I tried opening that link http://mauticurl/mailer/elasticemail/callback, it displays the sad Mautic gimmick with an internal server error message.

The instructions didn't mention setting up the webhooks:process cronjob but I did anyway just to see what happened, didn't change. The webhooks dashboard on my Mautic install is empty though.

I didn't yet add Elastic Emails SPF records to my domain's DNS setup but I don't think that could be related. 

Sending mail from Mautic through Elastic Email's smtp and the tracking of delivery/bounce statistics work on the Elastic dashboard. At first it didn't. I tried selecting "Elastic Email" on the email service options, entered my credentials, it said my account didn't exist. I needed to select "Other SMTP", then my credentials worked. After I selected again "Elastic Email" without changing anything else, it worked that way too.

Because some logs mention "permission denied", I tried resetting files and folders permissions, also cleared cache. That didn't change things.

I won't lie, maybe there's something I'm missing by inexperience. It's my first install.

Thanks for looking into it.

Edit: I was testing for blocks that my server might have to prevent outside domains from posting into a php file within my domain. Apparently there's nothing of the sort.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1.18-1

### Steps to reproduce:

I log into Elastic Email, go to Settings -> Notification > HTTP Web > Notification URL and set it to http://my-mautic-url/mailer/elasticemail/callback. Then I check Unsubscribed, Complaints, Bounce/Error and click on save.

 
### Log errors: 

The weird thing is that apparently nothing is logged in Apache when I try any of this. Later in the day some minimalistic messages appear, with the wrong times, so I'm not sure what triggers the logging or the lack of it. Cloudways support won't answer why there's nothing logged exactly when the error shows up, instead they blamed the custom app I'm using (Mautic).

Some logs I did see (don't know if related) from Apache:

[Thu Jun 21 20:48:56.975015 2018] [mpm_itk:warn] [pid 10294] (13)Permission denied: [client 127.0.0.1:54984] Couldn't read /path/to/www/s/ajax, closing connection., referer: https://my-mautic.tld/mailer/elasticmail/callback
[Thu Jun 21 20:58:16.604012 2018] [mpm_itk:warn] [pid 10762] (13)Permission denied: [client 127.0.0.1:55135] Couldn't read /path/to/www/mailer/elasticemail/callback, closing connection.

Then there're tons of error messages like this in my Mautic logs:

[2018-06-21 21:46:12] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "swiftmailer.mailer.transport.smtp"." at /path/to/www/vendor/symfony/dependency-injection/Container.php line 288 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"swiftmailer.mailer.transport.smtp\". at /path/to/www/vendor/symfony/dependency-injection/Container.php:288)"} []

The times look random to me.

**Comment by RafaelLVX** [comment]
Edit: I thought I had fixed it and related it in a comment, but I was wrong, the issue persists. Sorry about that.

**Comment by networkradixweb** [comment]
@RafaelLVX : How did you solve it ? using HTTP notification ? Can you please help ?

**Comment by RafaelLVX** [comment]
@networkradixweb I thought I had fixed it and related it in a comment, but I was wrong, the issue persists. Sorry about that.

**Comment by njolin** [comment]
Any fix for this yet?

**Comment by dsukhin** [comment]
having a related issue with the `/mailer/amazon/callback` endpoint:
```
mautic.CRITICAL: 
Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: 
"You have requested a non-existent service "swiftmailer.mailer.transport.mail". 
Did you mean this: "swiftmailer.mailer.default.transport.real"?" at
/home/mautic/vendor/symfony/dependency-injection/Container.php line 288 
```

Does bounce management callbacks work for anyone?

**Comment by npracht** [comment]
Hello @RafaelLVX @dsukhin @njolin @networkradixweb can you tell if https://github.com/mautic/mautic/pull/7015 solves your issue? Thanks !

**Comment by foxmedo** [comment]
i have same problem, im using  2.15.0 ? any suggestion

**Comment by npracht** [comment]
Solved in 2.15.1 with https://github.com/mautic/mautic/pull/7015

**Comment by RafaelLVX** [comment]
Unfortunately I still have the issue on a fresh 2.15.1 install.
