### ISSUE TITLE
Tags empty in Mautic webhooks

### ISSUE THREAD

**Issue by fuGii** [mautic/mautic#6861]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic webhook payload has empty tags array even though tags are defined for the contact. Webhook event is configured to "Contact Updated Event" and after contact update (e.g. manual points change or tags added/removed) webhook payload will return tags field as empty.

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.30
| Browser | Chrome

### Steps to reproduce
1. Create webhook for "Contact Updated Event".
2. Update contact's tags manually.
3. Debug webhook's payload and discover empty tags array.
 
### Log errors
No errors found in logs.

Webhook's payload:
https://pastebin.com/5kWZ1W9s

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Clement134** [comment]
The tagList element was not present in the serialization groups for contact webhooks. It should be fixed with #6899.

**Comment by atulshrma91** [comment]
Please check issue still persists https://pastebin.com/QTqAVwr8

Value of tags is empty.
