### ISSUE TITLE
Swift_IoException: Unable to open file for reading [{tracking_pixel}] caused by 'Append tracking pixel into email body'->'Yes'

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#9069]
### Bug Description
Following upgrade to 3.0.2, 'Append tracking pixel into email body'->Yes causes Swift_IoException: Unable to open file for reading [{tracking_pixel}]. 

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.21
| Browser | Safari 13.1.2

### Steps to reproduce
1. Enable Configuration->Email Settings->'Append tracking pixel into email body'->Yes
2. Observe mautic log file. 
3. Send test email from Configuration->Email Settings->'Send test email' button.
4. Observe email file appearing in var/spool/ - it gets renamed to several sending states, until it finally reaches e.g. `jUl5D6VcM.message.finalretry`
5. Observe Mautic log in var/log. (see log below)
6. Observe several instances of 'tracking_pixel' inserted in the email spool file `jUl5D6VcM.message.finalretry` without any actual path/filename: `a:1:{s:8:"filename";s:16:"{tracking_pixel}";`

I have checked this is not a directory/file permissions issue (I have already seen several similar past bugs here). 
 
###  This issue also causes several other larger isues:
- Web Forms (which are set to email form results immediately (Form setting 'Send immediately'->Yes)) run **very** slowly. This causes bad end-user experience e.g. where Wordpress-Mautic form integration is used.
- The 'var/spool/jUl5D6VcM.message.finalretry' message continues to stay indefinitely in the spool directory and causes mautic:emails:send cronjob to always fail. I.e. any consequent spooled emails which do not have the 'tracking_pixel' issue are also blocked from sending. 

I have noticed this bug after an upgrade from Mautic v2.1.16 to v3.0.2 (I have not tested for this bug in 3.0.1). Issue could be related to upgrade not correctly updating the mautic files, or due to some core issues in v3.0.2. 

### Log errors Mautic Log
```
[2020-08-10 10:44:02] mautic.NOTICE: Swift_IoException: Unable to open file for reading [{tracking_pixel}] (uncaught exception) at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 131 while running console command `mautic:emails:send` [] []
[2020-08-10 10:44:02] mautic.WARNING: Command `mautic:emails:send` exited with status code 1 [] []
```

### Log errors Httpd
None logged. 

### Manually running 'php  bin/console  mautic:emails:send -vvv' provides a verbose trace:
```
In FileByteStream.php line 131:
                                                      
  [Swift_IoException]                                 
  Unable to open file for reading [{tracking_pixel}]  
                                                      

Exception trace:
  at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:131
 Swift_ByteStream_FileByteStream->getReadHandle() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:77
 Swift_ByteStream_FileByteStream->read() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/ContentEncoder/Base64ContentEncoder.php:40
 Swift_Mime_ContentEncoder_Base64ContentEncoder->encodeByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:555
 Swift_Mime_SimpleMimeEntity->bodyToByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:532
 Swift_Mime_SimpleMimeEntity->toByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:570
 Swift_Mime_SimpleMimeEntity->bodyToByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:532
 Swift_Mime_SimpleMimeEntity->toByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:570
 Swift_Mime_SimpleMimeEntity->bodyToByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:532
 Swift_Mime_SimpleMimeEntity->toByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:601
 Swift_Mime_SimpleMessage->toByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php:162
 Swift_Message->toByteStream() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:398
 Swift_Transport_AbstractSmtpTransport->streamMessage() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:500
 Swift_Transport_AbstractSmtpTransport->doMailTransaction() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:516
 Swift_Transport_AbstractSmtpTransport->sendTo() at mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:206
 Swift_Transport_AbstractSmtpTransport->send() at mautic/app/bundles/EmailBundle/Command/ProcessEmailQueueCommand.php:115
 Mautic\EmailBundle\Command\ProcessEmailQueueCommand->execute() at mautic/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at mautic/vendor/symfony/console/Application.php:1005
 Symfony\Component\Console\Application->doRunCommand() at mautic/vendor/symfony/framework-bundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at mautic/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at mautic/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at mautic/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at mautic/bin/console:43

mautic:emails:send [--message-limit [MESSAGE-LIMIT]] [--time-limit [TIME-LIMIT]] [--do-not-clear] [--recover-timeout [RECOVER-TIMEOUT]] [--clear-timeout [CLEAR-TIMEOUT]] [-f|--force] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

**Comment by DeanWookey** [comment]
See also #8908

**Comment by RCheesley** [comment]
Thanks for flagging this and for the detailed write up @evgu. I recall we did merge some changes relating to the embedding of the pixel in 3.0.2 https://github.com/mautic/mautic/pull/8967 - could well be related to that change.

@DeanWookey thanks for linking this up to the other issue as well!

**Comment by quadcom** [comment]
I'm caught by this one and it's shut down my entire email system. I didn't catch the issue before it was too late to restore a backup of 3.0.1.

As is stands, only certain emails are getting through but form submission form actions emails are not which means clients trying to get in touch won't be responded to. This is a big issue.

**Comment by RCheesley** [comment]
Have you tried with/without base64 encoding per the [comment in the issue](https://github.com/mautic/mautic/issues/8908#issuecomment-668080369)? Some folk had this problem when embedded images was turned on I believe.

**Comment by RCheesley** [comment]
@DeanWookey would you be able to make a PR based on your debugging in the other issue?

**Comment by quadcom** [comment]
> Have you tried with/without base64 encoding per the [comment in the issue](https://github.com/mautic/mautic/issues/8908#issuecomment-668080369)? Some folk had this problem when embedded images was turned on I believe.

I did find that and turned it off. I can't confirm for sure that campaign emails are going out. It all depends on whether emails are generated and queued and then the error pops up or if the error happens prior to emails being generated. In other words, will emails sitting in qeue still cause the error to happen?

I'll have to manually test to be sure.

**Comment by evgu** [comment]
> Have you tried with/without base64 encoding per the [comment in the issue](https://github.com/mautic/mautic/issues/8908#issuecomment-668080369)? Some folk had this problem when embedded images was turned on I believe.

@RCheesley  I can confirm that when 'Convert embed images to Base64' = 'Yes' then the bug is showing. Disabling base64 obscures this bug and emails send fine.

**Comment by LevryKurniawan** [comment]
> > Have you tried with/without base64 encoding per the [comment in the issue](https://github.com/mautic/mautic/issues/8908#issuecomment-668080369)? Some folk had this problem when embedded images was turned on I believe.
> 
> @RCheesley I can confirm that when 'Convert embed images to Base64' = 'Yes' then the bug is showing. Disabling base64 obscures this bug and emails send fine.

I also got the same thing.

**Comment by RCheesley** [comment]
Thanks all for chiming in. It looks like we need to take a deeper dive into the impact of base64 encoding on the tracking pixel in emails as this bug keeps on popping up with changes being made to this area of code.

Would anybody be up for tackling this issue?  

Timeline wise we have the 3.1.1 sprint on Friday and Saturday this week, if we miss the deadline for the Release Candidate freeze on Sunday the next opportunity to merge a fix would be at the end of October.

**Comment by evgu** [comment]
@RCheesley Can someone point me to which part of the code generates the email messges that are consequently placed in var/spool/ ? Something in there does not replace {tracking_pixel} with the correct tracking pixel URL, i.e. when the email-stub file is created.

**Comment by RCheesley** [comment]
Just reporting in that when I was trying to test #9080 I came across this problem in the same way as documented above.

**Comment by RCheesley** [comment]
@evgu in response to your questions, I think maybe this PR might have introduced the issue we are seeing: https://github.com/mautic/mautic/pull/8967 which was a change in this file: `app/bundles/EmailBundle/Helper/MailHelper.php`.

Some other PR's that might be related in the past were mentioned in this PR comment: https://github.com/mautic/mautic/pull/8967#issuecomment-660849818

The other file mentioned there is `app/bundles/EmailBundle/Event/EmailSendEvent.php`.

Guessing those are the two main places that might be causing the problem.

**Comment by RCheesley** [comment]
As we haven't been able to get a fix for this yet, I'm moving it back to 3.1.2 - it would be good to try and get it in for that release as it's a bit of a nasty one for folk who use base64.

**Comment by evgu** [comment]
@RCheesley, Patch below that fixes the tracking pixel errors when embed images to Base64 is enabled. Please arrange for PR and test. I have tested locally and it works. 

Issue was caused because the the `<img src="{tracking_image}` HTML tag containing the {tracking_image} token was converted into `<img src="cid:` when spooling the message. This further obscured the problem. When symfony:emails:send is called, it decodes the cid: back to "{tracking_pixel}",  but this happens after the tokens have been inserted in the message, thus avoiding the {tracking_image} token being converted to the correct tracking URL, which then causes the Swift_IOException. 

Below code simply adds a check if the <img> contains {tracking_pixel} and if so skips the call to embed the image. 

@alanhartless and @kuzmany For future reference: During debugging I noticed that MailHelper:setBody() is called at least 3-4 times after chosing a template email and about 5-6 times when sending the email, with various logical loops and repeat runs which seemed to me quite excessive. Perhaps wider overhaul of MailHelper.php is necessary. 

```
Index: app/bundles/EmailBundle/Helper/MailHelper.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- app/bundles/EmailBundle/Helper/MailHelper.php	(revision 08a6ae7e98c77caa584f84f0992118b36976cfdd)
+++ app/bundles/EmailBundle/Helper/MailHelper.php	(revision 7ec6ce3f4661f02b8358172fab7e72c03bcc239d)
@@ -980,7 +980,7 @@
         $content = strtr($content, $this->embedImagesReplaces);
         if (preg_match_all('/<img.+?src=[\"\'](.+?)[\"\'].*?>/i', $content, $matches)) {
             foreach ($matches[1] as $match) {
-                if (false === strpos($match, 'cid:')) {
+                if (false === strpos($match, 'cid:') && false === strpos($match, '{tracking_pixel}')) {
                     $this->embedImagesReplaces[$match] = $this->message->embed(\Swift_Image::fromPath($match));
                 }
             }

```

**Comment by evgu** [comment]
Potentially impacting: #9003 #8995

**Comment by mabumusa1** [comment]
@evgu I started a PR based on your code, may you please take the lead on testing, reviewing, and checking with others who are impacted by the same issue that you have. Thank you for your help

**Comment by evgu** [comment]
@mabumusa1 Thank you for the PR. I can certainly do the UAT. Did you create a new Mautic VM instance with this change where I can perform the tests and pass to other users to test too (I vaguelly recall it was part of the PR process)?

**Comment by npracht** [comment]
Fixed in 3.1.2

**Comment by J-Light** [comment]
@npracht we are using v3.2.1 and still see this issue. Would we want to re-open this or open a new issue.

**Comment by evgu** [comment]
@J-Light Can you post error logs related to this issue please and sequence of events/actions triggering the errors.

**Comment by DASAT** [comment]
I get the same error in Mautic 3.3.1. Can not open file image.jpg when base64 is turned on.
:(
Too bad.

Uli
