### ISSUE TITLE
Source code script uses grapejs builder as default (3.1.0)

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#9188]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've just merged source code from stage (3.1.0) to my local repository and noticed that email builder is not loading at all. It uses grapejs builder by default which as far as i know is optional. After replacing app.js and css.js from build (https://github.com/mautic/mautic/releases/download/3.1.0/3.1.0.zip) everything runs smoothly.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2
| Browser | Not related with issue

**Comment by npracht** [comment]
Can you point out exactly what you changed ?

**Comment by patrykgruszka** [comment]
@npracht those assets are completely different in source (staging branch, tag 3.1.0) and build package:
- /media/js/app.js on staging - 3,03 MB
- /media/js/app.js in [build package](https://github.com/mautic/mautic/releases/download/3.1.0/3.1.0.zip) - 357 KB
- /media/css/app.css on staging - 202 KB
- /media/css/app.css in [build package](https://github.com/mautic/mautic/releases/download/3.1.0/3.1.0.zip) - 131 KB

I've replaced those files and now email builder works fine.

**Comment by npracht** [comment]
So you mean that the issues are on staging files ? Am I understanding well ?

**Comment by npracht** [comment]
Okay, this commit is the issue https://github.com/mautic/mautic/commit/16564fbb96e89ad81317520655b563780d55b5dc

@dennisameling can you change that from staging asap ?

**Comment by patrykgruszka** [comment]
@npracht yes, exactly. The issues are on staging files.

**Comment by RCheesley** [comment]
If this is on Staging it will be in the 3.1 release as that commit is part of the release process I believe.   Has something gone wrong somewhere with a PR or a rebase maybe? Or maybe that PR to generate the assets was done where the new builder was installed?

**Comment by dennisameling** [comment]
Fixed in https://github.com/mautic/mautic/pull/9194. 

My laptop had the GrapeJS plugin installed for testing a PR earlier. Apparently this ended up in the production assets in the staging branch. This didn't affect our production releases, as the build process always regenerates production assets from a clean git clone. So it only affected users who cloned Mautic from GitHub.

Sorry for the inconvenience @patrykgruszka

**Comment by tungda** [comment]
I have the same issue. And even replace the app.js & app.css files as @patrykgruszka above mentioned & clear the cache also but still the same.

**Comment by RCheesley** [comment]
> I have the same issue. And even replace the app.js & app.css files as @patrykgruszka above mentioned & clear the cache also but still the same.

Please pull down the latest staging branch if you checked out from Git?
