### ISSUE TITLE
Accented characters in mail from field are replaced by � when using Amazon SES API

### ISSUE THREAD

**Issue by lukacsaron** [mautic/mautic#9345]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Email from field accented characters are becoming �s when sending through Amazon SES API. The issue is not existing when sending through Amazon SES SMTP.

This is the closest possible cause of the issue I could find on Amazon's documentation:

"If you want to use Unicode characters in the “friendly from” name, you must encode the “friendly from” name using MIME encoded-word syntax, as described in Sending raw email using the Amazon SES API."

and

"To maintain compatibility with older systems, Amazon SES honors the 7-bit ASCII limitation of SMTP as defined in RFC 2821. If you want to send content that contains non-ASCII characters, you must encode those characters into a format that uses 7-bit ASCII characters."

[https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html](url)

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.4.11
| Browser | Chrome 86.0.4240.111

### Steps to reproduce
1. Set up Mautic with Amazon SES API as a mailer
2. Send out an email with accented characters in the "mail from" field, like Áron Lukács or any of the Hungarian chars (öüóőúéáűí)
3. Notice the bad encoding (�ron Luk�cs) when the email is delivered
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mabumusa1** [comment]
Please check this PR, it should solve this issue

https://github.com/mautic/mautic/pull/9290

**Comment by npracht** [comment]
closing in favor of https://github.com/mautic/mautic/issues/8903

**Comment by r-martins** [comment]
It seems to me that the mentioned #8903 has nothing to do with the accented characters when using SES API.
The problem still persists on v. 3.2.2.

**Comment by mabumusa1** [comment]
@r-martins please check this PR https://github.com/mautic/mautic/pull/9434, it should handle unicode characters in the from name and email address. if it works for you please leave a review on the PR so we can merge it in the next release

**Comment by r-martins** [comment]
Thanks for that @mabumusa1.
I was able to implement your change, tested and commented there (#9434).
I hope they merge your contribution in the next release.
