### ISSUE TITLE
Adding custom field with type select/multiselect trough API with Oauth1 produces a 401 type code error

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#9481]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version 3.2| 
| PHP version 7.2| 
| Browser| 

### Steps to reproduce
Use Oauth1 for this request. Other authentications work.
```php
$data = array(
'label' => 'Shops (TB)',
'alias' => 'shops',
'type' => 'multiselect',
'isPubliclyUpdatable' => true,
'isUniqueIdentifier' => false,
'properties' => array(
'list' =>array( array( 'label' => 'label1', 'value' => 'value1' ),
array( 'label' => 'label2', 'value' => 'value2' )
)
)
);
$fieldApi = $api->newApi("contactFields", $auth, $apiUrl);
$response = $fieldApi->create($data);
```
The response has unexpected status code (401).

Response: 
```json
{"errors": [{"message": "It looks like we encountered an error (error # 401). Please report this to the administrator if it happens again.", "Code ": 401," type ": null}]}
```
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Please look into the logs what the actual error is.

**Comment by escopecz** [comment]
I've created a functional test that confirms there is no issue creating multiselect fields. I've used your payload. See https://github.com/mautic/mautic/pull/9498

It must be an issue in your configuration. Are other API requests working? 401 would suggest there is an authentication issue.

**Comment by laabidi21** [comment]
Log Files:
[2020-12-15 09:18:19] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "signature_invalid" at /var/www/html/mautic/vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php line 244 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): signature_invalid at /var/www/html/mautic/vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php:244)
[stacktrace]
#0 /var/www/html/mautic/app/bundles/ApiBundle/Security/OAuth1/Authentication/Provider/OAuthProvider.php(47): Bazinga\\OAuthServerBundle\\Service\\OAuthServerService->validateRequest(Array, 'POST', 'http://172.16.8...')
#1 /var/www/html/mautic/vendor/symfony/security/Core/Authentication/AuthenticationProviderManager.php(76): Mautic\\ApiBundle\\Security\\OAuth1\\Authentication\\Provider\\OAuthProvider->authenticate(Object(Bazinga\\OAuthServerBundle\\Security\\Authentification\\Token\\OAuthToken))
#2 /var/www/html/mautic/app/bundles/ApiBundle/Security/OAuth1/Firewall/OAuthListener.php(41): Symfony\\Component\\Security\\Core\\Authentication\\AuthenticationProviderManager->authenticate(Object(Bazinga\\OAuthServerBundle\\Security\\Authentification\\Token\\OAuthToken))
#3 /var/www/html/mautic/vendor/symfony/security/Http/Firewall.php(111): Mautic\\ApiBundle\\Security\\OAuth1\\Firewall\\OAuthListener->handle(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#4 /var/www/html/mautic/vendor/symfony/security/Http/Firewall.php(84): Symfony\\Component\\Security\\Http\\Firewall->handleRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), Object(Generator))
#5 /var/www/html/mautic/vendor/symfony/security-bundle/EventListener/FirewallListener.php(48): Symfony\\Component\\Security\\Http\\Firewall->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#6 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Bundle\\SecurityBundle\\EventListener\\FirewallListener->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#7 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#8 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#9 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#10 /var/www/html/mautic/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/mautic/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/mautic/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#18 /var/www/html/mautic/index.php(24): Stack\
un(Object(Stack\\StackedHttpKernel))
#19 {main}
"}

**Comment by laabidi21** [comment]
@escopecz the others API requests working normally.
the others Fields work normally: type: text, date, datetime, url, ... 

only the two types "select" and "multiselect" do not work

**Comment by escopecz** [comment]
Can you do some more experimentation to narrow down the problem? What comes to mind is to try to create the field without any options. Or with different authentication method. It clearly works in the functional test.

**Comment by laabidi21** [comment]
@escopecz I changed the authentication to OAuth2 and it works correctly for the creation of fields with type "select" and "multiselect"

**Comment by escopecz** [comment]
Great found. I updated the description accordingly.

**Comment by npracht** [comment]
Closed by https://github.com/mautic/mautic/pull/9498
Fixed in 3.2.2

**Comment by laabidi21** [comment]
@escopecz I installed Mautic 3.2.5 and I still have the same problem With type select/multiselect trough API with Oauth1 produces type code error.
