### ISSUE TITLE
500 Internal Server Error: Report when use Multi Touch Attributions as data source and filter by Segment

### ISSUE THREAD

**Issue by Uebix** [mautic/mautic#9617]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
500 Internal Server Error: Report when use Multi Touch Attributions as data source and filter by Segment

| Q   | A
| --- | ---
| Mautic version | 3.2.4
| PHP version | 7.3.26
| Browser | Chrome

### Steps to reproduce
1. Create a report with Multi Touch Attributions as data source and filter by Segment
2. Execute or Save report
 
### Log errors

SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\DBAL\Driver\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause'

Similar bug: https://github.com/mautic/mautic/issues/8365 and https://github.com/mautic/mautic/pull/8746
Simiral fix: https://github.com/mautic/mautic/pull/8746

**Comment by RCheesley** [comment]
Is this persisting in 3.2.5 as we merged some of the fixes you mention in the release?

**Comment by Uebix** [comment]
I have update mautic to 3.2.5 and yes, the problem persist on 3.2.5.

[2021-01-29 19:51:51] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT (SELECT count(*) FROM campaign_lead_event_log multilog INNER JOIN campaign_events multie ON multilog.event_id = multie.id INNER JOIN campaigns multic ON multie.campaign_id = multic.id WHERE (multie.event_type = 'decision') AND (multilog.lead_id = log.lead_id) GROUP BY multilog.lead_id) activity_count, `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`email` AS email FROM leads l INNER JOIN campaign_lead_event_log log ON l.id = log.lead_id LEFT JOIN stages s ON l.stage_id = s.id INNER JOIN campaign_events e ON log.event_id = e.id INNER JOIN campaigns c ON log.campaign_id = c.id WHERE (l.attribution_date IS NULL OR (DATE(l.attribution_date) BETWEEN ? AND ?)) AND ((e.event_type = 'decision') AND (log.is_scheduled = 0) AND (l.attribution IS NOT NULL) AND (l.attribution <> 0) AND (DATE(CONVERT_TZ(log.date_triggered,'UTC','Europe/Rome')) <= DATE(l.attribution_date))) AND (s.leadlist_id = ?)) c' with params ["2020-12-28", "2021-01-29", "3"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause'" at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT (SELECT count(*) FROM campaign_lead_event_log multilog INNER JOIN campaign_events multie ON multilog.event_id = multie.id INNER JOIN campaigns multic ON multie.campaign_id = multic.id WHERE (multie.event_type = 'decision') AND (multilog.lead_id = log.lead_id) GROUP BY multilog.lead_id) activity_count, `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`email` AS email FROM leads l INNER JOIN campaign_lead_event_log log ON l.id = log.lead_id LEFT JOIN stages s ON l.stage_id = s.id INNER JOIN campaign_events e ON log.event_id = e.id INNER JOIN campaigns c ON log.campaign_id = c.id WHERE (l.attribution_date IS NULL OR (DATE(l.attribution_date) BETWEEN ? AND ?)) AND ((e.event_type = 'decision') AND (log.is_scheduled = 0) AND (l.attribution IS NOT NULL) AND (l.attribution <> 0) AND (DATE(CONVERT_TZ(log.date_triggered,'UTC','Europe/Rome')) <= DATE(l.attribution_date))) AND (s.leadlist_id = ?)) c' with params [\"2020-12-28\", \"2021-01-29\", \"3\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []

**Comment by namratasaun** [comment]
hello, I got a 500 error when i selected email sent as the data source and used group by name. without group by it is working fine.
My mautic version - 3.2

**Comment by Masho123** [comment]
Hello Dear All, 

i am new and install mautic thour cpanel on subdomain using it smoothly but 3 days ago i create user and and going to adjust setting roles for my new user via my administrator account after save setting. my mautic give me error 500 like this and giving me access to log in my administrator account and showing this error 

Issue 1:
Message i received every time when i try to login to my admin accout:
Uh oh! I think I broke it. If I do it again, please report me to the system administrator!
500 Internal Server Error
------

Important :
the user i created through my admin account that user working and login access fine and smoothly by mautic.

Error Message i fount from my cpanel error is below i past it here 

Error i receive in log:
[2021-11-23 16:43:22] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DATE_FORMAT(t.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM campaign_leads t INNER JOIN campaigns c ON c.id = c.campaign_id WHERE (t.date_added BETWEEN ? AND ?) AND (c.created_by = ?) GROUP BY DATE_FORMAT(t.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.date_added, '%Y-%m-%d') ASC LIMIT 32' with params ["2021-10-23 00:00:00", "2021-11-23 23:59:59", 1]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.campaign_id' in 'on clause'" at /home/beuuiflm/memautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DATE_FORMAT(t.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM campaign_leads t INNER JOIN campaigns c ON c.id = c.campaign_id WHERE (t.date_added BETWEEN ? AND ?) AND (c.created_by = ?) GROUP BY DATE_FORMAT(t.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.date_added, '%Y-%m-%d') ASC LIMIT 32' with params [\"2021-10-23 00:00:00\", \"2021-11-23 23:59:59\", 1]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.campaign_id' in 'on clause' at /home/beuuiflm/memautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.campaign_id' in 'on clause' at /home/beuuiflm/memautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.campaign_id' in 'on clause' at /home/beuuiflm/memautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112)"} []

Please Let me know how to resolve this issue i am not coder and not familiar with command line give me solution for hosting c panel setting  etc

I am waiting for your solutions Brothers and sisters please help me and guide me how to fix this issue

Best Regards
Muhammad Ashfaq
